# Generated by Django 5.1.1 on 2024-09-18 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_moodentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductEntry',
        ),
    ]
