# Generated by Django 5.1.1 on 2024-10-01 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        # Menambahkan field 'image' ke model ProductEntry
        # Ini memungkinkan pengguna untuk mengunggah gambar produk
        # Field ini opsional (blank=True, null=True) dan gambar akan disimpan di folder 'product_images/'

        migrations.AddField(
            model_name='productentry',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        # Menambahkan field 'time' ke model ProductEntry
        # Ini akan mencatat waktu pembuatan entri produk secara otomatis
        # Field ini wajib diisi dan akan menggunakan waktu saat ini sebagai nilai default
    ]
